version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: yarn update
          command: |
            "npm install -g yarn"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: yarn check
          command: yarn test
      - run:
          name: lint check
          command: yarn lint
      - run:
          name: format check
          command: yarn format:check
      - run:
          name: coverage threshold
          command: yarn test:cov
      - run:
          name: E2E check
          command: yarn test:e2e
      - run:
          name: coverage threshold
          command: yarn test:cov
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: build and push docker image
          command: docker build -t mustafasayilgan/atolye15-app:v1 .
