# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
      name: Install dependencies
      command: yarn install
  - &build-packages
    run:
      name: Build
      command: yarn run build
  - &run-unit-tests
    run:
      name: Test
      command: yarn run test
unit-tests-template: &unit-tests-template
  working_directory: ~/nest
  steps:
    - checkout
    - *restore-cache
    - *install-deps
    - *build-packages
    - *run-unit-tests
unit-tests: &unit-tests
steps: -checkout
  yarn lint
  yarn format:check
  yarn test
  yarn test:cov
  yarn test:e2e
